#+TITLE: Summary

 This report looked at the emergence of ordered complex structures from natural phenomena and iterative processes.

Primarily the investigation is concerned with fractals, complex shapes that tend
to exhibit some sort of a pattern (e.g. snowflakes and coastlines), formally a definition for a fractal is actually quite a nuanced problem and
is not something that appears to have been completely settled in the literature something discussed within the report.

In order to investigate fractals this report provides methods to generate a variety of self-similar and non-self-similar fractals and measure a corresponding descriptive metric known as the /fractal dimension/.




- This lead to investicaging fractals
- In order to define fractals we needed to extend the concept of dimension to non-integer values.

- Looked at ways to generate self similar fractals and the processes that lead the emergence of such patterns
  + looked at connections between somewhat random processes such as the chaos game and mathematical objects like Pascal's triangle
  + Wrote programs to draw fractals by performing a walk

  + Considered a real world observation of such a fractal.

  + Designed a fractal that showed a relationship between the fibonacci numbers and the golden ratio.

- Simulated non-self-similar fractals and implemented a strategy to measure the dimension of such a shape in an applied setting.
